version: '3.8'

services:

  kosmos_test:
    image: postgres:latest
    environment:
      POSTGRES_USER: kosmos_test
      POSTGRES_PASSWORD: kosmos_test
      POSTGRES_DB: kosmos_test
    ports:
      - "5432:5432"
    volumes:
      - ./infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - kosmos_test-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  kosmos_test-data:
  pgadmin-data: