CREATE TABLE IF NOT EXISTS public.users
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "firstName" text COLLATE pg_catalog."default",
    "lastName" text COLLATE pg_catalog."default",
    "middleName" text COLLATE pg_catalog."default",
    login text COLLATE pg_catalog."default",
    password text COLLATE pg_catalog."default",
    "managerId" integer,
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.users OWNER to kosmos_test;

INSERT INTO public.users ("firstName", "lastName", "middleName", login, password, "managerId", "createdAt", "updatedAt")
VALUES ('User', 'Userov', 'Userovich', 'user', 'password', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


CREATE TABLE IF NOT EXISTS public.tasks
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    title text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    priority text COLLATE pg_catalog."default",
    status text COLLATE pg_catalog."default",
    "creatorId" integer,
    "assigneeId" integer,
    deadline timestamp with time zone,
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone,
    CONSTRAINT tasks_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.tasks OWNER to kosmos_test;